name: insightops_dart
description: Unofficial wrapper for using Rapid7 insightOps logs (former LogEntries) with Dart.
version: 0.0.1
homepage: https://www.example.com
author: Kirill Bubochkin <ookami.kb@gmail.com>

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  logging: ^0.11.3+2
  http: ^0.12.0+2

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
