name: insightops_dart
description: Unofficial wrapper for using Rapid7 insightOps logs (former LogEntries) with Dart.
version: 0.3.0
homepage: https://github.com/ookami-kb/insightops_dart

environment:
  sdk: ^3.2.0

dependencies:
  async: ^2.11.0
  http: ^1.2.1
  logging: ^1.2.0

dev_dependencies:
  mews_pedantic: ^0.26.0
  test: ^1.25.4
