name: insightops_dart
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com
# author: ookami <ookami.kb@gmail.com>

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  logging: ^0.11.3+2
  http: ^0.12.0+2

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
